import { vi } from 'vitest';

const mockEditor = {
  getValue: vi.fn(() => ''),
  setValue: vi.fn(),
  getModel: vi.fn(() => ({
    getLanguageId: vi.fn(() => 'typescript'),
  })),
  onDidChangeModelContent: vi.fn(() => ({ dispose: vi.fn() })),
  dispose: vi.fn(),
  focus: vi.fn(),
  getAction: vi.fn(() => ({ run: vi.fn() })),
  addCommand: vi.fn(),
  addKeybindingRule: vi.fn(),
  updateOptions: vi.fn(),
  layout: vi.fn(),
  getScrollTop: vi.fn(() => 0),
  setScrollTop: vi.fn(),
  getScrollLeft: vi.fn(() => 0),
  setScrollLeft: vi.fn(),
  getContribution: vi.fn(),
  getContainerDomNode: vi.fn(() => document.createElement('div')),
  getDomNode: vi.fn(() => document.createElement('div')),
  getPosition: vi.fn(() => ({ lineNumber: 1, column: 1 })),
  setPosition: vi.fn(),
  getSelection: vi.fn(),
  setSelection: vi.fn(),
  revealLine: vi.fn(),
  revealLineInCenter: vi.fn(),
  revealPosition: vi.fn(),
  revealPositionInCenter: vi.fn(),
  trigger: vi.fn(),
};

const mockModel = {
  uri: { fsPath: '/test.ts', scheme: 'file' },
  getValue: vi.fn(() => ''),
  setValue: vi.fn(),
  getLanguageId: vi.fn(() => 'typescript'),
  getLineCount: vi.fn(() => 1),
  getLineMaxColumn: vi.fn(() => 1),
  getValueInRange: vi.fn(() => ''),
  getWordAtPosition: vi.fn(),
  getWordUntilPosition: vi.fn(),
  onDidChangeContent: vi.fn(() => ({ dispose: vi.fn() })),
  dispose: vi.fn(),
};

export const editor = {
  create: vi.fn(() => mockEditor),
  createDiffEditor: vi.fn(() => mockEditor),
  createModel: vi.fn(() => mockModel),
  onDidCreateEditor: vi.fn(),
  defineTheme: vi.fn(),
  setTheme: vi.fn(),
  addKeybindingRules: vi.fn(),
  addCommand: vi.fn(),
  setModelLanguage: vi.fn(),
  setModelMarkers: vi.fn(),
  getModels: vi.fn(() => []),
  getModel: vi.fn(() => mockModel),
};

export const languages = {
  register: vi.fn(),
  setMonarchTokensProvider: vi.fn(),
  registerCompletionItemProvider: vi.fn(),
  registerHoverProvider: vi.fn(),
  registerDefinitionProvider: vi.fn(),
  registerReferenceProvider: vi.fn(),
  registerSignatureHelpProvider: vi.fn(),
  registerDocumentFormattingEditProvider: vi.fn(),
  registerDocumentRangeFormattingEditProvider: vi.fn(),
  registerOnTypeFormattingEditProvider: vi.fn(),
  registerCodeLensProvider: vi.fn(),
  registerCodeActionProvider: vi.fn(),
  registerColorProvider: vi.fn(),
  registerDeclarationProvider: vi.fn(),
  registerDocumentHighlightProvider: vi.fn(),
  registerDocumentSemanticTokensProvider: vi.fn(),
  registerDocumentSymbolProvider: vi.fn(),
  registerFoldingRangeProvider: vi.fn(),
  registerImplementationProvider: vi.fn(),
  registerLinkedEditingRangeProvider: vi.fn(),
  registerRenameProvider: vi.fn(),
  registerSelectionRangeProvider: vi.fn(),
  registerTypeDefinitionProvider: vi.fn(),
  registerTypeHierarchyProvider: vi.fn(),
  registerWorkspaceSymbolProvider: vi.fn(),
  registerInlineCompletionsProvider: vi.fn(),
  registerLinkedEditingRangeProvider: vi.fn(),
};

export const KeyCode = {
  KeyS: 49,
  KeyZ: 50,
  KeyY: 51,
  KeyF: 52,
  KeyG: 53,
  KeyH: 54,
  KeyK: 55,
  KeyL: 56,
  KeyP: 57,
  KeyQ: 58,
  KeyR: 59,
  KeyT: 60,
  KeyW: 61,
  KeyX: 62,
  KeyC: 63,
  KeyV: 64,
  KeyA: 65,
  KeyB: 66,
  KeyD: 67,
  KeyE: 68,
  KeyI: 69,
  KeyJ: 70,
  KeyM: 71,
  KeyN: 72,
  KeyO: 73,
  KeyU: 74,
  Key0: 75,
  Key1: 76,
  Key2: 77,
  Key3: 78,
  Key4: 79,
  Key5: 80,
  Key6: 81,
  Key7: 82,
  Key8: 83,
  Key9: 84,
  Numpad0: 85,
  Numpad1: 86,
  Numpad2: 87,
  Numpad3: 88,
  Numpad4: 89,
  Numpad5: 90,
  Numpad6: 91,
  Numpad7: 92,
  Numpad8: 93,
  Numpad9: 94,
  NumpadMultiply: 95,
  NumpadAdd: 96,
  NumpadSeparator: 97,
  NumpadSubtract: 98,
  NumpadDecimal: 99,
  NumpadDivide: 100,
  F1: 101,
  F2: 102,
  F3: 103,
  F4: 104,
  F5: 105,
  F6: 106,
  F7: 107,
  F8: 108,
  F9: 109,
  F10: 110,
  F11: 111,
  F12: 112,
  F13: 113,
  F14: 114,
  F15: 115,
  F16: 116,
  F17: 117,
  F18: 118,
  F19: 119,
  F20: 120,
  F21: 121,
  F22: 122,
  F23: 123,
  F24: 124,
  NumLock: 125,
  ScrollLock: 126,
  SemiColon: 127,
  Equal: 128,
  Comma: 129,
  Minus: 130,
  Period: 131,
  Slash: 132,
  Backquote: 133,
  BracketLeft: 134,
  Backslash: 135,
  BracketRight: 136,
  Quote: 137,
  OEM_8: 138,
  IntlBackslash: 139,
  NumpadEqual: 140,
  MediaTrackPrevious: 141,
  MediaTrackNext: 142,
  MediaPlayPause: 143,
  MediaStop: 144,
  VolumeDown: 145,
  VolumeUp: 146,
  VolumeMute: 147,
  BrowserHome: 148,
  LaunchMediaPlayer: 149,
  LaunchMail: 150,
  LaunchApp2: 151,
  IntlYen: 152,
  Undo: 153,
  Redo: 154,
  SelectAll: 155,
  Cut: 156,
  Copy: 157,
  Paste: 158,
  Tab: 159,
  Enter: 160,
  Backspace: 161,
  Delete: 162,
  Insert: 163,
  Home: 164,
  End: 165,
  PageUp: 166,
  PageDown: 167,
  UpArrow: 168,
  DownArrow: 169,
  LeftArrow: 170,
  RightArrow: 171,
  Escape: 172,
  Space: 173,
  Shift: 174,
  Ctrl: 175,
  Alt: 176,
  Meta: 177,
  CapsLock: 178,
  ContextMenu: 179,
  OS: 180,
  Hyper: 181,
  Super: 182,
  Fn: 183,
  FnLock: 184,
  Suspend: 185,
  Resume: 186,
  Turbo: 187,
  Sleep: 188,
  WakeUp: 189,
  Wakeup: 190,
  ToggleDisplay: 191,
  BrightnessUp: 192,
  BrightnessDown: 193,
  KeyboardLayoutSelect: 194,
  KeyboardLayoutUp: 195,
  KeyboardLayoutDown: 196,
  KeyboardLayoutAs: 197,
  KeyboardLayoutDv: 198,
  KeyboardLayoutCl: 199,
  KeyboardLayoutCo: 200,
  KeyboardLayoutAk: 201,
  KeyboardLayoutGb: 202,
  KeyboardLayoutHax: 203,
  KeyboardLayoutPl: 204,
  KeyboardLayoutRo: 205,
  KeyboardLayoutRu: 206,
  KeyboardLayoutSw: 207,
  KeyboardLayoutUs: 208,
  KeyboardLayoutZh: 209,
  KeyboardLayoutJa: 210,
  KeyboardLayoutKo: 211,
  KeyboardLayoutAr: 212,
  KeyboardLayoutHe: 213,
  KeyboardLayoutTh: 214,
  KeyboardLayoutVi: 215,
  KeyboardLayoutHi: 216,
  KeyboardLayoutBn: 217,
  KeyboardLayoutPa: 218,
  KeyboardLayoutGu: 219,
  KeyboardLayoutOr: 220,
  KeyboardLayoutTa: 221,
  KeyboardLayoutTe: 222,
  KeyboardLayoutKn: 223,
  KeyboardLayoutMl: 224,
  KeyboardLayoutSi: 225,
  KeyboardLayoutMy: 226,
  KeyboardLayoutKa: 227,
  KeyboardLayoutAm: 228,
  KeyboardLayoutTi: 229,
  KeyboardLayoutNe: 230,
  KeyboardLayoutMr: 231,
  KeyboardLayoutSa: 232,
  KeyboardLayoutKu: 233,
  KeyboardLayoutPs: 234,
  KeyboardLayoutFa: 235,
  KeyboardLayoutUg: 236,
  KeyboardLayoutKk: 237,
  KeyboardLayoutKy: 238,
  KeyboardLayoutTg: 239,
  KeyboardLayoutTk: 240,
  KeyboardLayoutUz: 241,
  KeyboardLayoutMn: 242,
  KeyboardLayoutBo: 243,
  KeyboardLayoutDz: 244,
  KeyboardLayoutCy: 245,
  KeyboardLayoutEu: 246,
  KeyboardLayoutCa: 247,
  KeyboardLayoutGl: 248,
  KeyboardLayoutAst: 249,
  KeyboardLayoutAn: 250,
  KeyboardLayoutAy: 251,
  KeyboardLayoutQu: 252,
  KeyboardLayoutGn: 253,
  KeyboardLayoutAy2: 254,
  KeyboardLayoutQu2: 255,
};

export const MarkerSeverity = {
  Hint: 1,
  Info: 2,
  Warning: 4,
  Error: 8,
};

export const MarkerTag = {
  Unnecessary: 1,
  Deprecated: 2,
};

export const CompletionItemKind = {
  Method: 0,
  Function: 1,
  Constructor: 2,
  Field: 3,
  Variable: 4,
  Class: 5,
  Struct: 6,
  Interface: 7,
  Module: 8,
  Property: 9,
  Event: 10,
  Operator: 11,
  Unit: 12,
  Value: 13,
  Enum: 14,
  Keyword: 15,
  Snippet: 16,
  Color: 17,
  File: 18,
  Reference: 19,
  Folder: 20,
  EnumMember: 21,
  Constant: 22,
  Struct: 23,
  Event: 24,
  Operator: 25,
  TypeParameter: 26,
  User: 27,
  Issue: 28,
};

export const CompletionItemInsertTextRule = {
  None: 0,
  KeepWhitespace: 1,
  InsertAsSnippet: 4,
  AsIs: 8,
};

export const CompletionTriggerKind = {
  Invoke: 0,
  TriggerCharacter: 1,
  TriggerForIncompleteCompletions: 2,
};

export const InlineCompletionTriggerKind = {
  Automatic: 0,
  Explicit: 1,
};

export default {
  editor,
  languages,
  KeyCode,
  MarkerSeverity,
  MarkerTag,
  CompletionItemKind,
  CompletionItemInsertTextRule,
  CompletionTriggerKind,
  InlineCompletionTriggerKind,
};
